# Generated by Django 5.1.3 on 2024-11-19 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='personal_email',
            field=models.CharField(blank=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(validators=[django.core.validators.EmailValidator]),
        ),
    ]
